data = {
    "start":"id5",
    "persons": {
        "id1": { "id": "id1", "name": "Joseph Flynn", "birthyear": 1864, "deathyear": 1940, "own_unions": [], "parent_union": "u7", "birthplace":"Mohill", "deathplace":"Cloonbo" },
        "id2": { "id": "id2", "name": "Mary Flynn", "birthyear": 1866, "deathyear": 1936, "own_unions": [], "parent_union": "u7" },
        "id3": { "id": "id3", "name": "James Flynn", "birthyear": 1868, "deathyear": 1909, "own_unions": [], "parent_union": "u7" },
        "id4": { "id": "id4", "name": "Peter Flynn", "birthyear": 1870, "own_unions": [], "parent_union": "u7" },
        "id5": { "id": "id5", "name": "Michael Flynn", "birthyear": 1873, "deathyear": 1940, "own_unions": ["u1"], "parent_union": "u7"},
        "id6": { "id": "id6", "name": "Margaret Flynn", "birthyear": 1877, "deathyear": 1970, "own_unions": [], "parent_union": "u7", "birthplace":"Mohill" },
        "id7": { "id": "id7", "name": "Kate Whelan", "birthyear": 1880, "deathyear": 1915, "own_unions": ["u1"] },
        "id8": { "id": "id8", "name": "Mary Ann (Mary) Flynn", "birthyear": 1906, "deathyear": 1970, "own_unions": ["u2"], "parent_union": "u1" },
        "id9": { "id": "id9", "name": "Margaret (Maggie/Peggie) Flynn", "birthyear": 1907, "deathyear": 2000, "own_unions": ["u3"], "parent_union": "u1" },
        "id10": { "id": "id10", "name": "James (Jim) Flynn", "birthyear": 1909, "deathyear": 1968, "own_unions": ["u4"], "parent_union": "u1" },
        "id11": { "id": "id11", "name": "Patrick (Pat) Flynn", "birthyear": 1911, "deathyear": 1997, "own_unions": ["u5"], "parent_union": "u1" },
        "id12": { "id": "id12", "name": "Kate (Katie) Flynn", "birthyear": 1913, "deathyear": 1994, "own_unions": ["u6"], "parent_union": "u1" },
        "id13": { "id": "id13", "name": "Ellen (Ellie) Flynn", "birthyear": 1915, "deathyear": 2005, "own_unions": [], "parent_union": "u1" },
        "id14": { "id": "id14", "name": "Charles Flynn", "own_unions": ["u2"] },
        "id15": { "id": "id15", "name": "Thomas (Tom) Mahon", "own_unions": ["u3"] },
        "id16": { "id": "id16", "name": "Katheen (Baby) Gilroy", "own_unions": ["u4"] },
        "id17": { "id": "id17", "name": "Anna McGivern", "own_unions": ["u5"] },
        "id18": { "id": "id18", "name": "Michael Mulhern", "own_unions": ["u6"] },
        "id19": { "id": "id19", "name": "Charles (Charlie) Flynn", "own_unions": [], "parent_union": "u2" },
        "id20": { "id": "id20", "name": "Mary Flynn", "own_unions": [], "parent_union": "u2" },
        "id21": { "id": "id21", "name": "Kathy Flynn", "own_unions": [], "parent_union": "u2" },
        "id22": { "id": "id22", "name": "Betty Mahon", "own_unions": [], "parent_union": "u3" },
        "id23": { "id": "id23", "name": "Rose Mahon", "own_unions": [], "parent_union": "u3" },
        "id24": { "id": "id24", "name": "Gerard (Gerry) Flynn", "own_unions": [], "parent_union": "u4" },
        "id25": { "id": "id25", "name": "Patricia (Patsy) Flynn", "own_unions": [], "parent_union": "u4" },
        "id26": { "id": "id26", "name": "Marian Flynn", "own_unions": [], "parent_union": "u4" },
        "id27": { "id": "id27", "name": "Michael Flynn", "own_unions": [], "parent_union": "u5" },
        "id28": { "id": "id28", "name": "James (Jimmy) Flynn", "own_unions": [], "parent_union": "u5" },
        "id29": { "id": "id29", "name": "Mary Flynn", "own_unions": [], "parent_union": "u5" },
        "id30": { "id": "id30", "name": "John Flynn", "own_unions": [], "parent_union": "u5" },
        "id31": { "id": "id31", "name": "Kathleen Flynn", "own_unions": [], "parent_union": "u5" },
        "id32": { "id": "id32", "name": "Patrick (Pat) Flynn", "own_unions": [], "parent_union": "u5" },
        "id33": { "id": "id33", "name": "Marie Mulhern", "own_unions": [], "parent_union": "u6" },
        "id34": { "id": "id34", "name": "Patrick Flynn", "own_unions": ["u7"], "parent_union": "" },
        "id35": { "id": "id35", "name": "Margaret McGuinness", "own_unions": ["u7"], "parent_union": "" },
    },
    "unions": {
        "u1": { "id": "u1", "partner": ["id5", "id7"], "children": ["id8", "id9", "id10", "id11", "id12", "id13"] },
        "u2": { "id": "u2", "partner": ["id8", "id14"], "children": ["id19", "id20", "id21"] },
        "u3": { "id": "u3", "partner": ["id9", "id15"], "children": ["id22", "id23"] },
        "u4": { "id": "u4", "partner": ["id10", "id16"], "children": ["id24", "id25", "id26"] },
        "u5": { "id": "u5", "partner": ["id11", "id17"], "children": ["id27", "id28", "id29", "id30", "id31", "id32"] },
        "u6": { "id": "u6", "partner": ["id12", "id18"], "children": ["id33"] }
        "u7": { "id": "u7", "partner": ["id34", "id35"], "children": ["id1", "id2", "id3", "id4", "id5", "id6"] },
    },
    "links": [
        ["id5", "u1"],
        ["id7", "u1"],
        ["u1", "id8"],
        ["u1", "id9"],
        ["u1", "id10"],
        ["u1", "id11"],
        ["u1", "id12"],
        ["u1", "id13"],
        ["id8", "u2"],
        ["id14", "u2"],
        ["u2", "id19"],
        ["u2", "id20"],
        ["u2", "id21"],
        ["id9", "u3"],
        ["id15", "u3"],
        ["u3", "id22"],
        ["u3", "id23"],
        ["id10", "u4"],
        ["id16", "u4"],
        ["u4", "id22"],
        ["u4", "id24"],
        ["u4", "id25"],
        ["u4", "id26"],
        ["id11", "u5"],
        ["id17", "u5"],
        ["u5", "id27"],
        ["u5", "id28"],
        ["u5", "id29"],
        ["u5", "id30"],
        ["u5", "id31"],
        ["u5", "id32"],
        ["id12", "u6"],
        ["id18", "u6"],
        ["u6", "id33"],
        ["id34", "u7"],
        ["id35", "u7"],
        ["u7", "id1"],
        ["u7", "id2"],
        ["u7", "id3"],
        ["u7", "id4"],
        ["u7", "id5"],
        ["u7", "id6"],
    ]
}